### PR TITLE
Added theme 'burn7_AnimePink'

### PR DESCRIPTION
**Pull request by BurnoutAg7**
~~Should've added to main directly.~~

Typoed. Thought this was my own repo.

### CODE REVIEW

**Comment by BurnoutAg7** [comment]
Wondering if I should edit the readme,or it's up to the maintainers?

**Comment by pfeerick** [comment]
You are more welcome to as part of the PR... just add it to the bottom of the list. One less job for us ;)

**Comment by BurnoutAg7** [comment]
Found out I turned off mail notifications. I think all the work is done now.

**Comment by pfeerick** [comment]
Looks good... thanks for that! :)

**Pull request merged**
