### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Romushock1**
### All Submissions:
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### New Theme Submissions:
Have you included all the required elements? 
1. [x] Have you included all the [required elements](../../themes#description-of-an-edgetx-theme) in your theme?
2. [x] Are images in the correct resolution?
3. [x] Have you updated the `readme.md` to include reference to your creation?

### CODE REVIEW

**Comment by Romushock1** [comment]
New theme.

**Comment by pfeerick** [comment]
Did you have some more work to do on this?

**Comment by Romushock1** [comment]
Hi Peter,I would like to add my theme to existing, but i'm new in github and probably make it wrong... I'll retry, under your supervision, OK?Best.Roman.14 февр. 2022 г. 2:06 пользователь Peter Feerick ***@***.***> написал:
Did you have some more work to do on this?

**Comment by pfeerick** [comment]
You can make multiple changes to a single branch on github if you get it wrong the first time, or need to make further changes, but it's probably hard if you're doing it from the web interface, rather from the github desktop client or some other desktop app. 

You were close with this PR, just:
- `Ram/Ram.png` should have been `Ram/background_480x272.png` 
- `Ram/Ram.yml` should have been `Ram/theme.yml`

Rest of the files looked fine. If you undelete/restore the branch I can do the rename here before merging. Do you have sources for the images used?

**Comment by Romushock1** [comment]
Hi Peter,

I've reload my theme once again. Hope this time will be OK.

Thanks a lot.

Best.

Roman.

**Pull request closed without merging**
