### PR TITLE
Wolf inspired theme

### PR DESCRIPTION
**Pull request by ulfhedlund**
### All Submissions:
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### New Theme Submissions:
Have you included all the required elements? 
1. [x] Have you included all the [required elements](../../themes#description-of-an-edgetx-theme) in your theme?
2. [x] Are images in the correct resolution?
3. [x] Have you updated the `readme.md` to include reference to your creation?

### CODE REVIEW

**Comment by pfeerick** [comment]
The `480x272.png` image (and also the logo.png) look a bit squashed also - did you want to crop rather than resize them also or are you happy with them as they are?

**Comment by ulfhedlund** [comment]
Ok, let me take a look at them again before merge./UlfDen 4 nov. 2022 00:38 skrev Peter Feerick ***@***.***>:
The 480x272.png image (and also the logo.png) look a bit squashed also - did you want to crop rather than resize them also or are you happy with them as they are?

**Comment by ulfhedlund** [comment]
Made some adjustments, images are good enough for now I think :)

**Review by pfeerick — APPROVED** [review]
LGTM - not squished anymore. Just thought I'd check since you mentioned you'd some resize issues already ;)

**Pull request merged**
