### PR TITLE
RCVR High Contrast Theme

### PR DESCRIPTION
**Pull request by jmxp69**

### CODE REVIEW

**Comment by pfeerick** [comment]
Just need the themefile#NUM files to be  RCVR_High_Contrast#NUM, and it will be added. Anyone would thing you fly heli from that models page ;)

**Comment by pfeerick** [comment]
On second thought, since I think you're uploading through github's web ui and it can be a pain, I'll just rename them and merge.

**Comment by pernstig** [comment]
I tried the RCVR High Contrast theme with disappointing results. Among other things, there was black text on a black background in some wigwets, which I tried to correct on all seven of my models. It didn't turn out well either, so I've returned to the default EdgeTx theme. Attached some screenshots for comparison using white and black backgrounds. I´m using TX16S on Edge TX 2.8.
Main view 1
Model Notes
Radio Settings_Telemetry

**Comment by jmxp69** [comment]
Feel free to edit so it works for you then.

**Pull request merged**
