### PR TITLE
GrownUp Theme

### PR DESCRIPTION
**Pull request by MadMonkey87**
### New Theme Submissions:
Have you included all the required elements? 
1. [x] Have you included all the [required elements](../../themes#description-of-an-edgetx-theme) in your theme?
2. [x] Are images in the correct resolution?
3. [x] Have you updated the `readme.md` to include reference to your creation?

image

### CODE REVIEW

**Comment by pfeerick** [comment]
Very nice looking! :) Are the widgets on the left side custom Lua scripts or are they available for download somewhere (just asking as if they are they are they could get added the [lua scripts repo](https://github.com/EdgeTX/lua-scripts))

**Comment by MadMonkey87** [comment]
Thx! Yes they are custom and can br found here: https://github.com/MadMonkey87/EdgeTX-Goodies

I need to complete a few things and then I'll open a pr😃

**Comment by pfeerick** [comment]
Oh, nice... will have to check those out later... and what reminds me of the gauge issue again 😆

**Comment by MadMonkey87** [comment]
Hehe yes, if I find the time to dig in the code I can fix it myself (my C times are looong gone)

**Pull request merged**
