### PR TITLE
Handpainted sky theme for 2.6

### PR DESCRIPTION
**Pull request by andersix**
### All Submissions:
* [x] Have you checked to ensure there aren't other open [Pull Requests](../pulls) for the same update/change?

### New Theme Submissions:
Have you included all the required elements? 
1. [x] Have you included all the [required elements](../../themes#description-of-an-edgetx-theme) in your theme?
2. [x] Are images in the correct resolution?
3. [x] Have you updated the `readme.md` to include reference to your creation?

### CODE REVIEW

**Comment by pfeerick** [comment]
This looks really nice! Did you intentionally want the double quotes to be shown in the theme description? If you didn't, either you or I can make the changes, just let me know. 

snapshot_01

**Comment by andersix** [comment]
> This looks really nice! Did you intentionally want the double quotes to be shown in the theme description? If you didn't, either you or I can make the changes, just let me know.
> 
I did not intend those quotes to be there. Also, I neglected to add the screenshots to the readme.md. Did you want me to make those changes? I'm easy either way. Thanks.

**Comment by andersix** [comment]
readme updated, double-quotes removed.

Cheers!

**Comment by pfeerick** [comment]
_Thank you_ for the great theme, and doing the changes while I napped / was busy! :)

**Pull request merged**
